include conf/distro/include/cargt-imx-base.inc
include conf/distro/include/cargt-imx-preferred-env.inc

DISTRO = "cargt-imx-wayland"

INIT_MANAGER = "systemd"

# Remove conflicting backends
DISTRO_FEATURES:remove = "directfb x11 "
DISTRO_FEATURES:append = " wayland pam systemd"

NETWORK_MANAGER = "networkmanager"
RDEPENDS:packagegroup-core-tools-testapps:remove = "connman-tools connman-tests connman-client "

VIRTUAL-RUNTIME_syslog = ""
VIRTUAL-RUNTIME_base-utils-syslog = ""